spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: guojian19860718
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: user
    password: password
  redis:
    host: 127.0.0.1
    port: 6379
env:
  test1314
girl:
  name: mo12
  age: 17
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  
